const NO_TRANSACTION_MARKER = /^\s*--\s*no-transaction(?:\s|$)/i;
const statement = `-- no-transaction
-- Migration: 0155_paranoid_fk_indexes.sql
-- Generated by Antigravity Deep-Research Agent

CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_clinics_organization_id" ON "clinics" ("organization_id");`;

console.log('Matches?', NO_TRANSACTION_MARKER.test(statement));
