[Interface]
PrivateKey = KJ1IkXVN+SAUAIdfsAJVHrjKhQ1kbUy7r94j4197zEQ=
Address = 10.77.0.4/32, fd77:77::4/128
DNS = 1.1.1.1, 1.0.0.1
MTU = 1280

[Peer]
PublicKey = prasa7UMfcbVdiR2nakjD4hQu2hGTJTf76P/n/dWBEA=
PresharedKey = vDykuILhlqD+CIMIHiB9E3aJGTCmDMvnODMrLwb+o/U=
AllowedIPs = 172.64.0.0/13, 104.16.0.0/12, 10.77.0.0/24
Endpoint = 62.84.100.97:443
PersistentKeepalive = 25
